services:
  db:
    image: postgres:latest
    container_name: my_db_compose
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_DB=Suchet
      - POSTGRES_USER=Suchet
      - POSTGRES_PASSWORD=Suchet
  app:
    image: prawee/strapi:latest
    container_name: my_app_compose
    ports:
      - "8080:1337"
    environment:
        DATABASE_HOST: 192.168.1.69
        DATABASE_PORT: 55432
        DATABASE_NAME: Suchet
        DATABASE_USERNAME: Suchet
        DATABASE_PASSWORD: Suchet